<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVatT7Se\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVatT7Se/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVatT7Se.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVatT7Se\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVatT7Se\App_KernelDevDebugContainer([
    'container.build_hash' => 'VatT7Se',
    'container.build_id' => '9bb0dbc6',
    'container.build_time' => 1757503300,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVatT7Se');
